---
sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
    makerFeeRate: 0%
    takerFeeRate: 0%

  #max:
  #  exchange: max
  #  envVarPrefix: max

riskControls:
  # This is the session-based risk controller, which let you configure different risk controller by session.
  sessionBased:
    # "max" is the session name that you want to configure the risk control
    max:
      # orderExecutor is one of the risk control
      orderExecutor:
        # symbol-routed order executor
        bySymbol:
          USDCUSDT:
            # basic risk control order executor
            basic:
              minQuoteBalance: 100.0
              maxBaseAssetBalance: 3.0
              minBaseAssetBalance: 0.0
              maxOrderAmount: 1000.0

# example command:
#    godotenv -f .env.local -- go run ./cmd/bbgo backtest --sync-from 2020-11-01 --config config/grid.yaml --base-asset-baseline
backtest:
  # for testing max draw down (MDD) at 03-12
  # see here for more details
  # https://www.investopedia.com/terms/m/maximum-drawdown-mdd.asp
  startTime: "2024-08-19"
  endTime: "2024-08-20"
  symbols:
    - USDCUSDT
  sessions: [binance]
  accounts:
    binance:
      makerFeeRate: 0.0%
      takerFeeRate: 0.0%
      balances:
        USDC: 0.0
        USDT: 10000.0

exchangeStrategies:

- on: binance
  grid:
    symbol: USDCUSDT
    quantity: 500
    # scaleQuantity:
    #   byPrice:
    #     exp:
    #       domain: [20_000, 30_000]
    #       range: [0.2, 0.001]
    gridNumber: 20
    profitSpread: 0.0001
    upperPrice: 1.001
    lowerPrice: 0.999
    # long: true  # The sell order is submitted in the same order amount as the filled corresponding buy order, rather than the same quantity.

sync:
  depositHistory: true
  marginHistory: true
  sessions:
  - binance
  symbols:
  - binance:USDCUSDT
  since: 2023-04-03
  userDataStream:
    filledOrders: true
    trades: true
  withdrawHistory: true

